name: Deploy workflow

on:
  push:
    branches:
      - main

env:
  AWS_REGION: sa-east-1
  AWS_ROLE: arn:aws:iam::807181840404:role/GithubActionsOIDC-Role-XhFeMhEOphGb

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9' 

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install CDK dependencies
      working-directory: ./cdk
      run:
        npm install

    - name: Run ESLint on CDK scripts
      working-directory: ./cdk
      run:
        npx eslint

    - name: Install Python dependencies
      working-directory: ./TestApp
      run: |
        pip install --user virtualenv
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      working-directory: ./TestApp/testapp
      env:
        REQUIRED_SETTING: foo
      run: |
        source ../venv/bin/activate
        ./test.sh

  cdk-deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install node dependencies
      working-directory: ./cdk
      run: npm install

    - name: CDK Deploy
      working-directory: ./cdk
      run: |
        export PATH="./node_modules/.bin:$PATH"
        cdk deploy \
          --progress events \
          --require-approval never \
          TestAppStack
