name: Deploy workflow

on:
  push:
    branches:
      - main

env:
  AWS_REGION: sa-east-1
  AWS_ROLE: arn:aws:iam::807181840404:role/GithubActionsOIDC-Role-XhFeMhEOphGb
  REPOSITORY: matific/test-app

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build docker image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:${{ github.sha }} .

    - name: Run tests
      run: |
        docker run -e REQUIRED_SETTING=foo ${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:${{ github.sha }} ./test.sh

    - name: Push docker image
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:${{ github.sha }}

  cdk-deploy:
    runs-on: ubuntu-latest
    needs: build-test-push
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install node dependencies
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: CDK Deploy
      run: |
        export PATH="./node_modules/.bin:$PATH"
        cdk deploy \
          --progress events \
          --require-approval never \
          --context repositoryArn=arn:aws:ecr:sa-east-1:807181840404:repository/matific/test-app \
          --context tag=${{ github.sha }} \
          --role-arn arn:aws:iam::807181840404:role/cdk-hnb659fds-deploy-role-807181840404-sa-east-1 \
          TestAppStack
